// Load .env file
require("dotenv").config({ path: "/home/clawdbot/clawd/skills/nomie-sre/.env" });

module.exports = {
  apps: [
    {
      name: "nomie-sre-daemon",
      script: "./dist/index.js",
      args: "daemon",
      cwd: "/home/clawdbot/clawd/skills/nomie-sre",
      interpreter: "/home/clawdbot/.bun/bin/bun",
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
        SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
        SENTRY_ORG: process.env.SENTRY_ORG,
        SENTRY_PROJECT: process.env.SENTRY_PROJECT,
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
        AUTO_FIX_ENABLED: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/home/clawdbot/clawd/skills/nomie-sre/logs/error.log",
      out_file: "/home/clawdbot/clawd/skills/nomie-sre/logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "nomie-sre-poller",
      script: "./dist/index.js",
      args: "poll",
      cwd: "/home/clawdbot/clawd/skills/nomie-sre",
      interpreter: "/home/clawdbot/.bun/bin/bun",
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
        SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
        SENTRY_ORG: process.env.SENTRY_ORG,
        SENTRY_PROJECT: process.env.SENTRY_PROJECT,
        POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
        POSTHOG_PROJECT_ID: process.env.POSTHOG_PROJECT_ID,
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION,
        AUTO_FIX_ENABLED: "true",
      },
      instances: 1,
      autorestart: false,
      cron_restart: "*/5 * * * *",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/home/clawdbot/clawd/skills/nomie-sre/logs/poll-error.log",
      out_file: "/home/clawdbot/clawd/skills/nomie-sre/logs/poll-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
